import AboutSection from "./components/common/HomeSection/AboutSection";
import CounterSection from "./components/common/HomeSection/CounterSection";
import HomeContact from "./components/common/HomeSection/HomeContact ";
import ProductCatalogue from "./components/common/HomeSection/ProductCatalogue ";
import ShopByCategory from "./components/common/HomeSection/ShopByCategory";
import HomeSlider from "./components/common/HomeSlider/HomePageSlider";


export default function Home() {
  return (
    <>
   <HomeSlider/>
   <HomeContact/>
   <AboutSection/>
   <CounterSection/>
   <ShopByCategory/>
   <ProductCatalogue/>
   </>
  );
}


export const metadata = {
  title: "Welcome to Care-tex",
  description: "Generated by create next app",
};